---
title: LLVM clang 18.1.8-1 test results

date: 2024-06-25 04:58:42 +0000

---

## Debian Linux x86_64

```txt
Tests summary for clang 18.1.8-1 on linux-x64 (Debian 12)

2152 test cases passed, 16 skipped

Verdict: tests accepted
```

### Successful tests

- adder ✓
- adder-shared ✓
- adder-static ✓
- atomic ✓
- clang-configuration ✓
- clangd-hello ✓
- clangd-unchecked-exception ✓
- cnrt-test ✓
- exception-locale ✓
- exception-reduced ✓
- global-terminate ✓
- hello-exception ✓
- hello-weak1-c ✓
- hello-weak2-cpp ✓
- hello1-c ✓
- hello2-cpp ✓
- llvm-binaries-start ✓
- longjmp-cleanup ✓
- normal ✓
- overload-new-cpp ✓
- probe1 ✓
- probe2 ✓
- setjmp ✓
- simple-exception ✓
- simple-hello-cout-one ✓
- simple-hello-cout-two ✓
- simple-hello-printf-one ✓
- simple-hello-printf-two ✓
- simple-int-exception ✓
- simple-objc ✓
- simple-str-exception ✓
- sleepy-threads-cv ✓
- throwcatch-main ✓
- unwind-strong-cpp ✓
- unwind-weak-cpp ✓
- weak-common ✓
- weak-defined-c ✓
- weak-duplicate-c ✓
- weak-override-c ✓
- weak-undef-c ✓
- weak-use-c ✓

### Skipped test cases

- static-sleepy-threads-cv-32
- static-gc-sleepy-threads-cv-32
- static-lto-sleepy-threads-cv-32
- static-gc-lto-sleepy-threads-cv-32
- static-lld-sleepy-threads-cv-32
- static-gc-lld-sleepy-threads-cv-32
- static-lto-lld-sleepy-threads-cv-32
- static-gc-lto-lld-sleepy-threads-cv-32
- static-sleepy-threads-cv-64
- static-gc-sleepy-threads-cv-64
- static-lto-sleepy-threads-cv-64
- static-gc-lto-sleepy-threads-cv-64
- static-lld-sleepy-threads-cv-64
- static-gc-lld-sleepy-threads-cv-64
- static-lto-lld-sleepy-threads-cv-64
- static-gc-lto-lld-sleepy-threads-cv-64

## Debian Linux aarch64

```txt
Tests summary for clang 18.1.8-1 on linux-arm64 (Debian 12)

1062 test cases passed, 8 skipped

Verdict: tests accepted
```

### Successful tests

- adder-shared ✓
- adder-static ✓
- atomic ✓
- clang-configuration ✓
- clangd-hello ✓
- clangd-unchecked-exception ✓
- cnrt-test ✓
- exception-locale ✓
- exception-reduced ✓
- global-terminate ✓
- hello-exception ✓
- hello-weak1-c ✓
- hello-weak2-cpp ✓
- hello1-c ✓
- hello2-cpp ✓
- llvm-binaries-start ✓
- longjmp-cleanup ✓
- normal ✓
- overload-new-cpp ✓
- probe1 ✓
- probe2 ✓
- setjmp ✓
- simple-exception ✓
- simple-hello-cout-one ✓
- simple-hello-cout-two ✓
- simple-hello-printf-one ✓
- simple-hello-printf-two ✓
- simple-int-exception ✓
- simple-objc ✓
- simple-str-exception ✓
- sleepy-threads-cv ✓
- throwcatch-main ✓
- unwind-strong-cpp ✓
- unwind-weak-cpp ✓
- weak-common ✓
- weak-defined-c ✓
- weak-duplicate-c ✓
- weak-override-c ✓
- weak-undef-c ✓
- weak-use-c ✓

### Skipped test cases

- static-sleepy-threads-cv
- static-gc-sleepy-threads-cv
- static-lto-sleepy-threads-cv
- static-gc-lto-sleepy-threads-cv
- static-lld-sleepy-threads-cv
- static-gc-lld-sleepy-threads-cv
- static-lto-lld-sleepy-threads-cv
- static-gc-lto-lld-sleepy-threads-cv

## Debian Linux armv7l

```txt
Tests summary for clang 18.1.8-1 on linux-arm (Debian 12)

798 test cases passed, 14 skipped

Verdict: tests accepted
```

### Successful tests

- adder-shared ✓
- adder-static ✓
- atomic ✓
- clang-configuration ✓
- clangd-hello ✓
- clangd-unchecked-exception ✓
- cnrt-test ✓
- exception-locale ✓
- exception-reduced ✓
- global-terminate ✓
- hello-exception ✓
- hello-weak1-c ✓
- hello-weak2-cpp ✓
- hello1-c ✓
- hello2-cpp ✓
- llvm-binaries-start ✓
- longjmp-cleanup ✓
- normal ✓
- overload-new-cpp ✓
- probe1 ✓
- probe2 ✓
- setjmp ✓
- simple-exception ✓
- simple-hello-cout-one ✓
- simple-hello-cout-two ✓
- simple-hello-printf-one ✓
- simple-hello-printf-two ✓
- simple-int-exception ✓
- simple-objc ✓
- simple-str-exception ✓
- sleepy-threads-cv ✓
- throwcatch-main ✓
- unwind-strong-cpp ✓
- unwind-weak-cpp ✓
- weak-common ✓
- weak-defined-c ✓
- weak-duplicate-c ✓
- weak-override-c ✓
- weak-undef-c ✓
- weak-use-c ✓

### Skipped test cases

- all-lto  --lto
- all-lto  --gc --lto
- all-lto  --lto --static-lib
- all-lto  --gc --lto --static-lib
- all-lto  --lto --static
- all-lto  --gc --lto --static
- all-lto  --lto --libc++ --crt --libunwind
- all-lto  --gc --lto --libc++ --crt --libunwind
- static-sleepy-threads-cv
- static-gc-sleepy-threads-cv
- static-lld-sleepy-threads-cv
- static-gc-lld-sleepy-threads-cv
- static-lto-lld-sleepy-threads-cv
- static-gc-lto-lld-sleepy-threads-cv

## macOS Darwin x86_64

```txt
Tests summary for clang 18.1.8-1 on darwin-x64 (macOS 12.7.5)

272 test cases passed, 0 skipped, 4 failed:

- xfail: lto-throwcatch-main
- xfail: gc-lto-throwcatch-main
- xfail: lto-lld-throwcatch-main
- xfail: gc-lto-lld-throwcatch-main

Verdict: tests reluctantly accepted
```

### Successful tests

- adder-shared ✓
- adder-static ✓
- atomic ✓
- clang-configuration ✓
- clangd-hello ✓
- clangd-unchecked-exception ✓
- cnrt-test ✓
- exception-locale ✓
- exception-reduced ✓
- global-terminate ✓
- hello-exception ✓
- hello-weak1-c ✓
- hello-weak2-cpp ✓
- hello1-c ✓
- hello2-cpp ✓
- llvm-binaries-start ✓
- longjmp-cleanup ✓
- normal ✓
- overload-new-cpp ✓
- setjmp ✓
- simple-exception ✓
- simple-hello-cout-one ✓
- simple-hello-cout-two ✓
- simple-hello-printf-one ✓
- simple-hello-printf-two ✓
- simple-int-exception ✓
- simple-objc ✓
- simple-str-exception ✓
- sleepy-threads-cv ✓
- unwind-strong-cpp ✓
- unwind-weak-cpp ✓
- weak-common ✓
- weak-defined-c ✓
- weak-duplicate-c ✓
- weak-override-c ✓
- weak-undef-c ✓
- weak-use-c ✓

### Failed test throwcatch-main

- throwcatch-main ✓
- gc-throwcatch-main ✓
- lto-throwcatch-main ✗
  ```txt
  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-x64/x86_64-apple-darwin21.6.0/tests/clang-xpack/xpacks/.bin/clang++ throwcatch-lib.cpp -shared -fpic -o libthrowcatch-lib.dylib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -flto -std=c++11]

  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-x64/x86_64-apple-darwin21.6.0/tests/clang-xpack/xpacks/.bin/clang++ throwcatch-main.cpp -o lto-throwcatch-main -L. -lthrowcatch-lib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -flto -std=c++11]

  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-x64/x86_64-apple-darwin21.6.0/tests/clang/c-cpp/lto-throwcatch-main ]
  not throwing
  throwing FirstException
  caught std::exception
  caught unexpected exception!
  throwing SecondException
  caught std::exception
  caught unexpected exception!
  throwing std::exception
  caught std::exception
  got errors

  Test "lto-throwcatch-main " failed, got exit code: 1, expected 0 :-(

  xfail: lto-throwcatch-main
  ```
- gc-lto-throwcatch-main ✗
  ```txt
  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-x64/x86_64-apple-darwin21.6.0/tests/clang-xpack/xpacks/.bin/clang++ throwcatch-lib.cpp -shared -fpic -o libthrowcatch-lib.dylib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -flto -ffunction-sections -fdata-sections -Wl,-dead_strip -std=c++11]

  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-x64/x86_64-apple-darwin21.6.0/tests/clang-xpack/xpacks/.bin/clang++ throwcatch-main.cpp -o gc-lto-throwcatch-main -L. -lthrowcatch-lib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -flto -ffunction-sections -fdata-sections -Wl,-dead_strip -std=c++11]

  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-x64/x86_64-apple-darwin21.6.0/tests/clang/c-cpp/gc-lto-throwcatch-main ]
  not throwing
  throwing FirstException
  caught std::exception
  caught unexpected exception!
  throwing SecondException
  caught std::exception
  caught unexpected exception!
  throwing std::exception
  caught std::exception
  got errors

  Test "gc-lto-throwcatch-main " failed, got exit code: 1, expected 0 :-(

  xfail: gc-lto-throwcatch-main
  ```
- lld-throwcatch-main ✓
- gc-lld-throwcatch-main ✓
- lto-lld-throwcatch-main ✗
  ```txt
  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-x64/x86_64-apple-darwin21.6.0/tests/clang-xpack/xpacks/.bin/clang++ throwcatch-lib.cpp -shared -fpic -o libthrowcatch-lib.dylib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -fuse-ld=lld -flto -std=c++11]

  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-x64/x86_64-apple-darwin21.6.0/tests/clang-xpack/xpacks/.bin/clang++ throwcatch-main.cpp -o lto-lld-throwcatch-main -L. -lthrowcatch-lib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -fuse-ld=lld -flto -std=c++11]

  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-x64/x86_64-apple-darwin21.6.0/tests/clang/c-cpp/lto-lld-throwcatch-main ]
  not throwing
  throwing FirstException
  caught std::exception
  caught unexpected exception!
  throwing SecondException
  caught std::exception
  caught unexpected exception!
  throwing std::exception
  caught std::exception
  got errors

  Test "lto-lld-throwcatch-main " failed, got exit code: 1, expected 0 :-(

  xfail: lto-lld-throwcatch-main
  ```
- gc-lto-lld-throwcatch-main ✗
  ```txt
  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-x64/x86_64-apple-darwin21.6.0/tests/clang-xpack/xpacks/.bin/clang++ throwcatch-lib.cpp -shared -fpic -o libthrowcatch-lib.dylib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -fuse-ld=lld -flto -ffunction-sections -fdata-sections -Wl,-dead_strip -std=c++11]

  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-x64/x86_64-apple-darwin21.6.0/tests/clang-xpack/xpacks/.bin/clang++ throwcatch-main.cpp -o gc-lto-lld-throwcatch-main -L. -lthrowcatch-lib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -fuse-ld=lld -flto -ffunction-sections -fdata-sections -Wl,-dead_strip -std=c++11]

  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-x64/x86_64-apple-darwin21.6.0/tests/clang/c-cpp/gc-lto-lld-throwcatch-main ]
  not throwing
  throwing FirstException
  caught std::exception
  caught unexpected exception!
  throwing SecondException
  caught std::exception
  caught unexpected exception!
  throwing std::exception
  caught std::exception
  got errors

  Test "gc-lto-lld-throwcatch-main " failed, got exit code: 1, expected 0 :-(

  xfail: gc-lto-lld-throwcatch-main
  ```

## macOS Darwin arm64

```txt
Tests summary for clang 18.1.8-1 on darwin-arm64 (macOS 14.5)

268 test cases passed, 0 skipped, 8 failed:

- xfail: lld-hello-exception
- xfail: lld-exception-reduced
- xfail: gc-lld-hello-exception
- xfail: gc-lld-exception-reduced
- xfail: lto-lld-hello-exception
- xfail: lto-lld-exception-reduced
- xfail: gc-lto-lld-hello-exception
- xfail: gc-lto-lld-exception-reduced

Verdict: tests reluctantly accepted
```

### Successful tests

- adder-shared ✓
- adder-static ✓
- atomic ✓
- clang-configuration ✓
- clangd-hello ✓
- clangd-unchecked-exception ✓
- cnrt-test ✓
- exception-locale ✓
- global-terminate ✓
- hello-weak1-c ✓
- hello-weak2-cpp ✓
- hello1-c ✓
- hello2-cpp ✓
- llvm-binaries-start ✓
- longjmp-cleanup ✓
- normal ✓
- overload-new-cpp ✓
- setjmp ✓
- simple-exception ✓
- simple-hello-cout-one ✓
- simple-hello-cout-two ✓
- simple-hello-printf-one ✓
- simple-hello-printf-two ✓
- simple-int-exception ✓
- simple-objc ✓
- simple-str-exception ✓
- sleepy-threads-cv ✓
- throwcatch-main ✓
- unwind-strong-cpp ✓
- unwind-weak-cpp ✓
- weak-common ✓
- weak-defined-c ✓
- weak-duplicate-c ✓
- weak-override-c ✓
- weak-undef-c ✓
- weak-use-c ✓

### Failed test exception-reduced

- exception-reduced ✓
- gc-exception-reduced ✓
- lto-exception-reduced ✓
- gc-lto-exception-reduced ✓
- lld-exception-reduced ✗
  ```txt
  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-arm64/aarch64-apple-darwin23.5.0/tests/clang-xpack/xpacks/.bin/clang++ exception-reduced.cpp -o lld-exception-reduced -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -fuse-ld=lld -std=c++11]

  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-arm64/aarch64-apple-darwin23.5.0/tests/clang/c-cpp/lld-exception-reduced ]
  libc++abi: terminating due to uncaught exception of type int
  /Users/runner/work/clang-xpack/clang-xpack/xpacks/@xpack-dev-tools/xbb-helper/scripts/wrappers.sh: line 475:  7071 Abort trap: 6           "${app_path}" "$@"

  Test "lld-exception-reduced " failed, got exit code: 134, expected 0 :-(

  xfail: lld-exception-reduced
  ```
- gc-lld-exception-reduced ✗
  ```txt
  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-arm64/aarch64-apple-darwin23.5.0/tests/clang-xpack/xpacks/.bin/clang++ exception-reduced.cpp -o gc-lld-exception-reduced -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -fuse-ld=lld -ffunction-sections -fdata-sections -Wl,-dead_strip -std=c++11]

  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-arm64/aarch64-apple-darwin23.5.0/tests/clang/c-cpp/gc-lld-exception-reduced ]
  libc++abi: terminating due to uncaught exception of type int
  /Users/runner/work/clang-xpack/clang-xpack/xpacks/@xpack-dev-tools/xbb-helper/scripts/wrappers.sh: line 475:  7940 Abort trap: 6           "${app_path}" "$@"

  Test "gc-lld-exception-reduced " failed, got exit code: 134, expected 0 :-(

  xfail: gc-lld-exception-reduced
  ```
- lto-lld-exception-reduced ✗
  ```txt
  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-arm64/aarch64-apple-darwin23.5.0/tests/clang-xpack/xpacks/.bin/clang++ exception-reduced.cpp -o lto-lld-exception-reduced -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -fuse-ld=lld -flto -std=c++11]

  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-arm64/aarch64-apple-darwin23.5.0/tests/clang/c-cpp/lto-lld-exception-reduced ]
  libc++abi: terminating due to uncaught exception of type int
  /Users/runner/work/clang-xpack/clang-xpack/xpacks/@xpack-dev-tools/xbb-helper/scripts/wrappers.sh: line 475:  8808 Abort trap: 6           "${app_path}" "$@"

  Test "lto-lld-exception-reduced " failed, got exit code: 134, expected 0 :-(

  xfail: lto-lld-exception-reduced
  ```
- gc-lto-lld-exception-reduced ✗
  ```txt
  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-arm64/aarch64-apple-darwin23.5.0/tests/clang-xpack/xpacks/.bin/clang++ exception-reduced.cpp -o gc-lto-lld-exception-reduced -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -fuse-ld=lld -flto -ffunction-sections -fdata-sections -Wl,-dead_strip -std=c++11]

  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-arm64/aarch64-apple-darwin23.5.0/tests/clang/c-cpp/gc-lto-lld-exception-reduced ]
  libc++abi: terminating due to uncaught exception of type int
  /Users/runner/work/clang-xpack/clang-xpack/xpacks/@xpack-dev-tools/xbb-helper/scripts/wrappers.sh: line 475:  9751 Abort trap: 6           "${app_path}" "$@"

  Test "gc-lto-lld-exception-reduced " failed, got exit code: 134, expected 0 :-(

  xfail: gc-lto-lld-exception-reduced
  ```

### Failed test hello-exception

- hello-exception ✓
- gc-hello-exception ✓
- lto-hello-exception ✓
- gc-lto-hello-exception ✓
- lld-hello-exception ✗
  ```txt
  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-arm64/aarch64-apple-darwin23.5.0/tests/clang-xpack/xpacks/.bin/clang++ hello-exception.cpp -o lld-hello-exception -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -fuse-ld=lld]

  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-arm64/aarch64-apple-darwin23.5.0/tests/clang/c-cpp/lld-hello-exception ]
  ctor 10
  ctor 9
  ctor 8
  ctor 7
  ctor 6
  ctor 5
  ctor 4
  ctor 3
  ctor 2
  ctor 1
  ctor 0
  dtor 0
  libc++abi: terminating due to uncaught exception of type std::exception: std::exception
  /Users/runner/work/clang-xpack/clang-xpack/xpacks/@xpack-dev-tools/xbb-helper/scripts/wrappers.sh: line 475:  7020 Abort trap: 6           "${app_path}" "$@"

  Test "lld-hello-exception " failed, got exit code: 134, expected 0 :-(

  xfail: lld-hello-exception
  ```
- gc-lld-hello-exception ✗
  ```txt
  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-arm64/aarch64-apple-darwin23.5.0/tests/clang-xpack/xpacks/.bin/clang++ hello-exception.cpp -o gc-lld-hello-exception -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -fuse-ld=lld -ffunction-sections -fdata-sections -Wl,-dead_strip]

  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-arm64/aarch64-apple-darwin23.5.0/tests/clang/c-cpp/gc-lld-hello-exception ]
  ctor 10
  ctor 9
  ctor 8
  ctor 7
  ctor 6
  ctor 5
  ctor 4
  ctor 3
  ctor 2
  ctor 1
  ctor 0
  dtor 0
  libc++abi: terminating due to uncaught exception of type std::exception: std::exception
  /Users/runner/work/clang-xpack/clang-xpack/xpacks/@xpack-dev-tools/xbb-helper/scripts/wrappers.sh: line 475:  7889 Abort trap: 6           "${app_path}" "$@"

  Test "gc-lld-hello-exception " failed, got exit code: 134, expected 0 :-(

  xfail: gc-lld-hello-exception
  ```
- lto-lld-hello-exception ✗
  ```txt
  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-arm64/aarch64-apple-darwin23.5.0/tests/clang-xpack/xpacks/.bin/clang++ hello-exception.cpp -o lto-lld-hello-exception -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -fuse-ld=lld -flto]

  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-arm64/aarch64-apple-darwin23.5.0/tests/clang/c-cpp/lto-lld-hello-exception ]
  ctor 10
  ctor 9
  ctor 8
  ctor 7
  ctor 6
  ctor 5
  ctor 4
  ctor 3
  ctor 2
  ctor 1
  ctor 0
  dtor 0
  libc++abi: terminating due to uncaught exception of type std::exception: std::exception
  /Users/runner/work/clang-xpack/clang-xpack/xpacks/@xpack-dev-tools/xbb-helper/scripts/wrappers.sh: line 475:  8757 Abort trap: 6           "${app_path}" "$@"

  Test "lto-lld-hello-exception " failed, got exit code: 134, expected 0 :-(

  xfail: lto-lld-hello-exception
  ```
- gc-lto-lld-hello-exception ✗
  ```txt
  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-arm64/aarch64-apple-darwin23.5.0/tests/clang-xpack/xpacks/.bin/clang++ hello-exception.cpp -o gc-lto-lld-hello-exception -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -L/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib -Wl,-rpath,/Users/runner/Library/xPacks/@xpack-dev-tools/clang/18.1.8-1.1/.content/lib/clang/18/lib/darwin -fuse-ld=lld -flto -ffunction-sections -fdata-sections -Wl,-dead_strip]

  [/Users/runner/work/clang-xpack/clang-xpack/build/darwin-arm64/aarch64-apple-darwin23.5.0/tests/clang/c-cpp/gc-lto-lld-hello-exception ]
  ctor 10
  ctor 9
  ctor 8
  ctor 7
  ctor 6
  ctor 5
  ctor 4
  ctor 3
  ctor 2
  ctor 1
  ctor 0
  dtor 0
  libc++abi: terminating due to uncaught exception of type std::exception: std::exception
  /Users/runner/work/clang-xpack/clang-xpack/xpacks/@xpack-dev-tools/xbb-helper/scripts/wrappers.sh: line 475:  9700 Abort trap: 6           "${app_path}" "$@"

  Test "gc-lto-lld-hello-exception " failed, got exit code: 134, expected 0 :-(

  xfail: gc-lto-lld-hello-exception
  ```

## Msys Windows x86_64

```txt
Tests summary for clang 18.1.8-1 on win32-x64 (Msys 3.4.10)

906 test cases passed, 0 skipped

Verdict: tests accepted
```

### Successful tests

- adder ✓
- adder-shared ✓
- atomic ✓
- autoimport-main ✓
- bufferoverflow ✓
- clang-configuration ✓
- cnrt-test ✓
- exception-locale ✓
- exception-reduced ✓
- global-terminate ✓
- hello-exception ✓
- hello-tls ✓
- hello-weak1-c ✓
- hello-weak2-cpp ✓
- hello1-c ✓
- hello2-cpp ✓
- idltest ✓
- llvm-binaries-start ✓
- longjmp-cleanup ✓
- normal ✓
- overload-new-cpp ✓
- setjmp ✓
- simple-exception ✓
- simple-hello-cout-one ✓
- simple-hello-cout-two ✓
- simple-hello-printf-one ✓
- simple-hello-printf-two ✓
- simple-int-exception ✓
- simple-objc ✓
- simple-str-exception ✓
- sleepy-threads-cv ✓
- throwcatch-main ✓
- tlstest-main ✓
- unwind-strong-cpp ✓
- unwind-weak-cpp ✓
- weak-common ✓
- weak-defined-c ✓
- weak-duplicate-c ✓
- weak-override-c ✓
- weak-undef-c ✓
- weak-use-c ✓
